name: CronJob
on:
  schedule:
    - cron: "*/60 * * * *" # every hour
  push:
env:
  ETHEREUM_GOERLI_RPC_URL: ${{secrets.ETHEREUM_GOERLI_RPC_URL}}
  ETHEREUM_SEPOLIA_RPC_URL: ${{secrets.ETHEREUM_SEPOLIA_RPC_URL}}
  POLYGON_MUMBAI_RPC_URL: ${{secrets.POLYGON_MUMBAI_RPC_URL}}
jobs:
  runCLI:
    name: PrizePool Prizes Computation
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node: ["18.16.0"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        id: installDependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - name: Install PoolTogether V5 CLI
        run: |
          npm install -g @pooltogether/v5-cli@0.0.1-beta.9
          echo "$(npm -g bin)" >> $GITHUB_PATH
      # -------------------------------------------------------- #
      # Mumbai
      # -------------------------------------------------------- #
      - name: Mumbai Draw Prizes
        id: drawPrizesMumbai
        uses: chuckbergeron/executable-wrapper@f94b435740d6b958c2d7eb76c77657e761819cfe
        continue-on-error: true
        with:
          run_command: ptv5 compute drawPrizes -o ./api/prizes -p 0xA32C8f94191c9295634f0034eb2b0e2749e77974 -c 80001
      # -------------------------------------------------------- #
      # Sepolia
      # -------------------------------------------------------- #
      - name: Sepolia Draw Prizes
        id: drawPrizesSepolia
        uses: chuckbergeron/executable-wrapper@f94b435740d6b958c2d7eb76c77657e761819cfe
        continue-on-error: true
        with:
          run_command: ptv5 compute drawPrizes -o ./api/prizes -p 0xa77D6014e77F294C3297a18363f9951b3d57Eb95 -c 11155111
      # -------------------------------------------------------- #
      # Comment Error
      # -------------------------------------------------------- #
      - name: Comment Error
        id: commentError
        if: steps.drawPrizesMumbai.outputs.exitcode == 1 || steps.drawPrizesSepolia.outputs.exitcode == 1
        uses: actions/github-script@v5
        continue-on-error: true
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Draw Prizes Failed: Exit Code ${process.env.exitCode} (${process.env.errorcode})`
            })
      # -------------------------------------------------------- #
      # Git Commit
      # TODO: Use actions/github-script@v5 to complete commits
      # -------------------------------------------------------- #
      - name: Commit Mumbai
        if: steps.drawPrizesMumbai.outputs.runStatus == 'true'
        continue-on-error: true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add ./api/prizes/80001
          git commit -m "Add draw winners for Mumbai - Draw #${{steps.drawPrizesMumbai.outputs.drawId}}"
      - name: Commit Sepolia
        if: steps.drawPrizesSepolia.outputs.runStatus == 'true'
        continue-on-error: true
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add ./api/prizes/4/0x509a479885019fdcd1bb39cd982d1ab11857ce1d/0x95448a041d34241177b375a65efb34c61ad9e2b3/
          git commit -m "Add draw for Sepolia draw #${{steps.drawPrizesSepolia.outputs.drawId}}"
      # -------------------------------------------------------- #
      # Push Draw Prizes Computation
      # -------------------------------------------------------- #
      - name: Push changes (if required)
        uses: ad-m/github-push-action@master
        if: steps.drawPrizesMumbai.outputs.runStatus == 'true' || steps.drawPrizesSepolia.outputs.runStatus == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
